// This file generated by Piggy. Do not edit.
namespace Csharp
{
    using System;
    using System.Runtime.InteropServices;
    [StructLayout(LayoutKind.Sequential)]
    public partial struct struct1
    {
        public int a;
        public int b;
    }
}
